In [4]:
import nltk
from nltk.corpus import stopwords
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import TruncatedSVD

In [5]:
from sklearn.datasets import fetch_20newsgroups
categories = ['rec.sport.baseball']
dataset = fetch_20newsgroups(subset='all',shuffle=True, random_state=42, categories=categories)
corpus = dataset.data

In [6]:
from sklearn.datasets import fetch_20newsgroups

In [7]:
categories = ['rec.sport.baseball']

In [8]:
dataset = fetch_20newsgroups(subset='all',shuffle=True, random_state=42, categories=categories)

In [9]:
corpus = dataset.data

In [10]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\alemayehu\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.


True

In [11]:
stopset = set(stopwords.words('english'))
stopset.update(['lt','p','/p','br','amp','quot','field','font','normal','span','0px','rgb','style','51', 
                'spacing','text','helvetica','size','family', 'space', 'arial', 'height', 'indent', 'letter'
                'line','none','sans','serif','transform','line','variant','weight','times', 'new','strong', 'video', 'title'
                'white','word','letter', 'roman','0pt','16','color','12','14','21', 'neue', 'apple', 'class',  ])

In [12]:
corpus[0]

"From: writingctr@leo.bsuvc.bsu.edu\nSubject: Re: CUB fever.\nOrganization: Ball State University, Muncie, In - Univ. Computing Svc's\nLines: 21\n\n\nIn article <kingoz.735285670@camelot>, kingoz@camelot.bradley.edu (Orin Roth) writes:\n> \n>    CUB fever is hitting me again. I'm beginning to think they have a \n>    chance this year. (what the heck am i thinking?)\n>    Sorry. Just a moment of incompetence.\n>    I'll be ok. Really. \n>    Orin.\n>    Bradley U.\n> \n> --\n> I'm really a jester in disguise!                                   \nI hear ya!  Then again, we must remember that we are indeed Cub fans, and\nthat the Cubs will eventually blow it.  After all, the Cubs are the easiest\nteam in the National League to root for.  No Pressure.  You know they will\nlose eventually.  Oh well, I suppose we must have faith.  After all, they\ndo look pretty good, and they don't even have Sandberg back yet.  \n\nCUBS IN '93!!!!!\n\nCHA\n"

In [13]:
vectorizer = TfidfVectorizer(stop_words=stopset,
                                 use_idf=True, ngram_range=(1, 3))

In [14]:
X = vectorizer.fit_transform(corpus)

In [15]:
X[0]

<1x188088 sparse matrix of type '<class 'numpy.float64'>'
	with 229 stored elements in Compressed Sparse Row format>

In [16]:
print([0])

[0]


In [17]:
print(X[0])

  (0, 184845)	0.0739614450823
  (0, 98618)	0.0498392719888
  (0, 38760)	0.0508660032618
  (0, 38750)	0.0508660032618
  (0, 59766)	0.0238944824554
  (0, 160356)	0.0102587509246
  (0, 51363)	0.161996512624
  (0, 67979)	0.1253821105
  (0, 120881)	0.0103415667199
  (0, 29461)	0.0308265507854
  (0, 157546)	0.0374880148692
  (0, 173892)	0.0180626374482
  (0, 113507)	0.0611096618209
  (0, 173856)	0.039417195873
  (0, 48163)	0.0390694082984
  (0, 162430)	0.0611096618209
  (0, 100274)	0.0103208000105
  (0, 25764)	0.0161922460089
  (0, 94387)	0.111160461941
  (0, 16584)	0.0739614450823
  (0, 40682)	0.105257944488
  (0, 37508)	0.0996785439776
  (0, 121494)	0.111160461941
  (0, 142480)	0.0555802309707
  (0, 183911)	0.015655015889
  :	:
  (0, 64172)	0.0739614450823
  (0, 35716)	0.0739614450823
  (0, 51481)	0.0739614450823
  (0, 59267)	0.0739614450823
  (0, 164212)	0.0739614450823
  (0, 114349)	0.0739614450823
  (0, 97593)	0.0739614450823
  (0, 142244)	0.0739614450823
  (0, 132283)	0.0739614450823
 

In [18]:
X.shape

(994, 188088)

In [25]:
lsa = TruncatedSVD(n_components=10, n_iter=100,
       random_state=None, tol=0.0)

In [26]:
lsa.fit(X)

TruncatedSVD(algorithm='randomized', n_components=10, n_iter=100,
       random_state=None, tol=0.0)

In [27]:
lsa.components_[0]

array([ 0.01601322,  0.00499985,  0.00078314, ...,  0.00105261,
        0.00105261,  0.00105261])

In [28]:
lsa = TruncatedSVD(n_components=10, n_iter=100)
lsa.fit(X)

TruncatedSVD(algorithm='randomized', n_components=10, n_iter=100,
       random_state=None, tol=0.0)

In [29]:
lsa.components_[1]

array([-0.0098717 , -0.00295137, -0.0006629 , ..., -0.00051765,
       -0.00051765, -0.00051765])

In [30]:
lsa.components_[2]

array([ 0.02401288,  0.00544923,  0.00208006, ...,  0.00021722,
        0.00021722,  0.00021722])

In [31]:
import sys
print (sys.version)

3.6.0 |Anaconda 4.3.0 (32-bit)| (default, Dec 23 2016, 12:06:52) [MSC v.1900 32 bit (Intel)]


In [32]:
terms = vectorizer.get_feature_names()
for i, comp in enumerate(lsa.components_): 
    termsInComp = zip (terms,comp)
    sortedTerms =  sorted(termsInComp, key=lambda x: x[1], reverse=True) [:10]
    print("Concept %d:" % i )
    for term in sortedTerms:
        print(term[0])
    print (" ")

Concept 0:
edu
com
year
writes
team
would
game
article
cs
baseball
 
Concept 1:
jewish
lafayette
lafibm
vb30
jewish baseball
edu vb30
lafayette edu
lafayette edu vb30
lafibm lafayette
lafibm lafayette edu
 
Concept 2:
indiana
journalism
journalism indiana
journalism indiana edu
indiana edu
dwarner
dwarner journalism
dwarner journalism indiana
03
02
 
Concept 3:
03
02
04
05
01
lost
06
03 03
07
00
 
Concept 4:
duke
gatech
duke edu
gatech edu
prism
econ duke
econ
georgia
econ duke edu
fls
 
Concept 5:
gatech
prism
gatech edu
georgia
prism gatech
prism gatech edu
gt0523e
mule
michael
institute technology
 
Concept 6:
ibm
aix
kingston
ibm com
mjones
aix kingston
aix kingston ibm
kingston ibm
kingston ibm com
com
 
Concept 7:
bonds
williams
batting
stanford
batting 4th
punjabi
4th
leland
leland stanford
leland stanford edu
 
Concept 8:
tesla
njit
njit edu
tesla njit
tesla njit edu
best first
mattingly
drm6640
drm6640 tesla
drm6640 tesla njit
 
Concept 9:
jhu
jhu edu
hcf
hcf jhu
hcf jhu edu
j